/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import java.io.File

fun main() {
    val file = File("src/main/resources/list.txt")
    val list = file.readLines().map { 
    }
}
